### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by niosus** [randy3k/UnitTesting#44]
I have my tests in `tests` folder and they all start with `test*`. My `unittesting.json` is:
```json
{
    "tests_dir" : "tests",
    "pattern" : "test*.py",
    "async": true,
    "deferred": false,
    "verbosity": 5,
    "output": "<panel>",
}
```

If I try to test my package with these settings I get an error:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 536, in run_
    return self.run(**args)
  File "unittesting.test_runner in C:\Users\igor\AppData\Roaming\Sublime Text 3\Installed Packages\UnitTesting.sublime-package", line 163, in run
  File "unittesting.test_runner in C:\Users\igor\AppData\Roaming\Sublime Text 3\Installed Packages\UnitTesting.sublime-package", line 97, in load_settings
AttributeError: 'list' object has no attribute 'get'
```

If I remove the coma in the end of the `unittesting.json` everything turns back to normal and the tests are run.  This happens for me both on Windows and Linux.

**Comment by randy3k** [comment]
It was expected since it is invalid to have a comma at the end of a json. Sublime Test settings allow it since it uses a different parser. I have updated the related code to use the ST parser.

**Comment by randy3k** [comment]
Oh....I didn't aware that it is ST3 only feature...

**Comment by niosus** [comment]
Thanks!
