### ISSUE TITLE
PermissionError exception makes UnitTesting freeze

### ISSUE THREAD

**Issue by rwols** [randy3k/UnitTesting#58]
In the setUpClass class method of a fixture of mine I use `os.makedirs` in some places. When there's no permission to make dirs (in `/` for example), a `PermissionError` is thrown, but this freezes UnitTesting. Maybe account for this case?

**Comment by randy3k** [comment]
With this,
```
class TestFoo(DeferrableTestCase):

    @classmethod
    def setUpClass(cls):
        raise PermissionError("permission error")

```

The output panel prints
```
ERROR

======================================================================
ERROR: setUpClass (test_table.TestTable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/UnitTesting/unittesting/core/st3/suite.py", line 79, in _handleClassSetUp
    deferred = setUpClass()
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/AlignTab/tests/test_table.py", line 15, in setUpClass
    raise PermissionError("permission error")
PermissionError: permission error

----------------------------------------------------------------------
Ran 0 tests in 0.152s

FAILED (errors=1)

UnitTesting: Done.
```

The error was caught and it doesn't freeze UnitTesting!?

**Comment by rwols** [comment]
Yes, something else seems to be going wrong, sorry for the noise.
